name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello! Thanks for reporting a issue, Your issue will be checked."
        pr-message: "Hello! Thanks for making a pull request, I greatly appreciate your work."
